-- question-of-the-day pool (from questions.json)
insert into public.questions (id, text, category) values
  (1, 'What''s the first thing you noticed about me?', 'memories'),
  (2, 'What moment made you think ''okay, this one''s different''?', 'memories'),
  (3, 'What''s the hardest we''ve ever laughed together?', 'memories'),
  (4, 'Which of our early dates would you relive exactly as it was?', 'memories'),
  (5, 'What song instantly takes you back to when we started?', 'memories'),
  (6, 'What''s a tiny detail from our first meeting you''ve never told me you remember?', 'memories'),
  (7, 'What''s the best meal we''ve ever had together — and what made it the best?', 'memories'),
  (8, 'Which photo of us would you save first in a fire?', 'memories'),
  (9, 'What''s something silly we did early on that''s secretly still your favorite?', 'memories'),
  (10, 'When did you first feel completely at home with me?', 'memories'),
  (11, 'What''s a trip or outing of ours you think about more than you admit?', 'memories'),
  (12, 'What did we talk about for hours before life got busy?', 'memories'),
  (13, 'What''s the nicest thing a stranger ever witnessed us do?', 'memories'),
  (14, 'Which of our inside jokes has survived the longest?', 'memories'),
  (15, 'What''s a small gift I gave you that meant more than I probably realized?', 'memories'),
  (16, 'If we had a totally free Sunday and a tiny budget, what would we do?', 'fun'),
  (17, 'What would our couple band name be?', 'fun'),
  (18, 'If we opened a tiny shop together, what would it sell?', 'fun'),
  (19, 'Which fictional couple are we most like — honestly?', 'fun'),
  (20, 'What''s my most predictable habit — the one you could set a clock by?', 'fun'),
  (21, 'If we swapped phones for a day, what would make you laugh first?', 'fun'),
  (22, 'What would the title of a movie about us be?', 'fun'),
  (23, 'Which superpower would make us unstoppable as a team?', 'fun'),
  (24, 'What''s one food you''d fight me for the last bite of?', 'fun'),
  (25, 'If we had a mascot as a couple, what animal would it be?', 'fun'),
  (26, 'What''s the most ''us'' thing we could possibly do this weekend?', 'fun'),
  (27, 'If our life had a theme song that played when we entered rooms, what would it be?', 'fun'),
  (28, 'What game or sport should we absolutely never play against each other?', 'fun'),
  (29, 'What would we each pack first for a surprise midnight road trip?', 'fun'),
  (30, 'Which emoji is basically me?', 'fun'),
  (31, 'What''s something you''re proud of that you rarely say out loud?', 'deep'),
  (32, 'When do you feel most like yourself?', 'deep'),
  (33, 'What''s a fear that got smaller since we''ve been together?', 'deep'),
  (34, 'What does a perfect ordinary day look like to you — not a special one, an ordinary one?', 'deep'),
  (35, 'What''s something you learned about love from watching your family?', 'deep'),
  (36, 'What part of your life right now would your younger self be amazed by?', 'deep'),
  (37, 'What recharges you that you never make enough time for?', 'deep'),
  (38, 'What''s a dream you shelved that still visits you sometimes?', 'deep'),
  (39, 'What do you want to be known for by the people who love you?', 'deep'),
  (40, 'When was the last time you felt truly brave?', 'deep'),
  (41, 'What''s something you believe now that you didn''t three years ago?', 'deep'),
  (42, 'What does ''home'' mean to you — the feeling, not the place?', 'deep'),
  (43, 'What small kindness from someone do you still carry with you?', 'deep'),
  (44, 'If you could master one skill overnight, what would it be and why that one?', 'deep'),
  (45, 'What''s a compliment you received once and never forgot?', 'deep'),
  (46, 'Where should we wake up on our fifth anniversary?', 'future'),
  (47, 'What''s one tradition we should invent, just for us?', 'future'),
  (48, 'What does our dream kitchen look like — and who''s cooking in it?', 'future'),
  (49, 'What''s a skill we should learn together this year?', 'future'),
  (50, 'If money weren''t a thing for one year, what would we do with it?', 'future'),
  (51, 'What city should we get lost in someday?', 'future'),
  (52, 'What''s something small we could start doing every week that future-us would thank us for?', 'future'),
  (53, 'What kind of old couple do you hope we become?', 'future'),
  (54, 'What''s the next thing we should save up for after the current jar?', 'future'),
  (55, 'If we planted something today — a habit, a plan, a literal tree — what should it be?', 'future'),
  (56, 'What''s one adventure that scares us both a little but we should do anyway?', 'future'),
  (57, 'What would our home smell like on a perfect future evening?', 'future'),
  (58, 'What''s a holiday we''ve never celebrated properly that we should claim as ours?', 'future'),
  (59, 'Ten years from now, what do you hope is exactly the same about us?', 'future'),
  (60, 'What''s one thing you want us to be able to say we did while we were young?', 'future'),
  (61, 'What tiny thing did I do this month that you quietly loved?', 'us'),
  (62, 'When do you feel closest to me?', 'us'),
  (63, 'What''s something I do that instantly makes your day better?', 'us'),
  (64, 'What''s our superpower as a team?', 'us'),
  (65, 'What''s a way I show love that maybe I don''t realize I''m doing?', 'us'),
  (66, 'What did we do recently that felt completely, exactly like us?', 'us'),
  (67, 'What''s your favorite ordinary moment we share — the one nobody else would notice?', 'us'),
  (68, 'What''s something new you learned about me this year?', 'us'),
  (69, 'Which of my quirks did you find odd at first but now can''t imagine me without?', 'us'),
  (70, 'What''s a place that feels like it belongs to just the two of us?', 'us'),
  (71, 'How can I make you feel loved this week — one concrete thing?', 'us'),
  (72, 'What''s the best decision we''ve made together so far?', 'us'),
  (73, 'What do you hope never changes about the way we talk to each other?', 'us'),
  (74, 'What''s something we''re better at together than either of us is alone?', 'us'),
  (75, 'If you could bottle one feeling from this relationship, which moment would you take it from?', 'us'),
  (76, 'What''s one thing about today you don''t want to forget?', 'gratitude'),
  (77, 'Who in your life deserves a thank-you they haven''t gotten yet?', 'gratitude'),
  (78, 'What''s something ordinary in our life that would amaze most people in history?', 'gratitude'),
  (79, 'What made you smile this week when you were alone?', 'gratitude'),
  (80, 'What''s a hard thing from your past you''re now weirdly grateful for?', 'gratitude'),
  (81, 'What''s the best thing you ate recently — and who would you want to share it with next time?', 'gratitude'),
  (82, 'What''s one thing your body did for you today that deserves credit?', 'gratitude'),
  (83, 'What tiny luxury in your daily routine would you defend fiercely?', 'gratitude'),
  (84, 'What''s something in our home you''re glad we have, even though it cost almost nothing?', 'gratitude'),
  (85, 'What''s a sound you love that most people never mention?', 'gratitude'),
  (86, 'What went right this month that we never actually celebrated?', 'gratitude'),
  (87, 'Which person made you who you are in a way they''ll never fully know?', 'gratitude'),
  (88, 'What''s a small win from this week that deserved confetti?', 'gratitude'),
  (89, 'What part of our routine would you miss most if it vanished tomorrow?', 'gratitude'),
  (90, 'What are you looking forward to that costs nothing at all?', 'gratitude')
on conflict (id) do update set text = excluded.text, category = excluded.category;
