/** Every user-facing string that carries tone lives here — the tone is a feature. */
export const copy = {
  feedEmpty: "nothing here yet — the ＋ button is how it all starts 💛",
  jarsEmpty: "no jars yet — start one together, even a small one 🫙",
  bucketEmpty: "no dreams written down yet — add the first one 🌈",
  memsEmpty: "no moments in this stretch — the ＋ is waiting ✨",
  quietDay: "a quiet day — nothing spent, nothing logged",
  futureDay: "nothing here yet — this day is still on its way",
  savedToday: (n) => (n > 0 ? "into your jars today ✨" : "the jars are waiting today 👀"),
  spentNothing: "nothing yet — cheap date 😌",
  firstContribution: "no contributions yet — the first one is special 💛",
  pacePlain: "every little bit fills this jar ✨",
  goalDone: "DONE!! you two actually did it 🎉🎉",
  pingSent: (name) => `sent 💛 — ${name} will see it when they open Duo`,
  pingFrom: (name, when) => `💛 ${name} was thinking of you · ${when}`,
  leaveWarn: "Leaving means: everything you logged stays here with them, and you lose access to all of it — entries, photos, notes, jars. You can't undo this. Tap again to leave.",
  deleteWarn: "This deletes your account for good. If your person is still here, what you logged together stays with them; if not, the whole Duo and its photos are removed. Tap again to delete.",
  cycleFirstLog: (name) => `This starts tracking YOUR cycle on this account (${name}). If this rhythm is your person's, let them log it on their phone instead. Tap again to continue.`,
  pingBtn: "send a 💛 ping",
  checkInLock: "check in to see",
  qWait: (name) => `${name} has answered — yours goes first 🙈`,
  qWaitPartner: (name) => `waiting on ${name} — you'll both see them together 💛`,
  qSolo: "answer now — it reveals when you've both answered 💛",
  loginNoMatch: "no account matches that email + password yet. New here? Create one with these →",
  loginWrongPw: "that email already has an account — the password didn't match. Try again 💛",
  loginFail: "couldn't sign you in just now — check your connection and try again 💛",
  waitingTitle: "Waiting for your person 💛",
  linked: "You're linked! 🎉",
  noFight: "Duo shows facts about us, never accusations about you. No red. No alarms. Ever.",
};
