/** Every user-facing string that carries tone lives here — the tone is a feature. */
export const copy = {
  feedEmpty: "nothing here yet — the ＋ button is how it all starts 💛",
  jarsEmpty: "no jars yet — start one together, even a small one 🫙",
  bucketEmpty: "no dreams written down yet — add the first one 🌈",
  memsEmpty: "no moments in this stretch — the ＋ is waiting ✨",
  quietDay: "a quiet day — nothing spent, nothing logged",
  futureDay: "nothing here yet — this day is still on its way",
  savedToday: (n) => (n > 0 ? "into your jars today ✨" : "the jars are waiting today 👀"),
  spentNothing: "nothing yet — cheap date 😌",
  firstContribution: "no contributions yet — the first one is special 💛",
  pacePlain: "every little bit fills this jar ✨",
  goalDone: "DONE!! you two actually did it 🎉🎉",
  pingSent: (name) => `sent — ${name} will feel it 💛`,
  pingBtn: "send a 💛 ping",
  checkInLock: "check in to see",
  qWait: (name) => `${name} has answered — yours goes first 🙈`,
  qWaitPartner: (name) => `waiting on ${name} — you'll both see them together 💛`,
  qSolo: "answer now — it reveals when you've both answered 💛",
  emailSent: "Check your email — we sent a link and a 6-digit code 💌",
  emailFail: "the email couldn't send just now — give it a minute and try again 💛",
  waitingTitle: "Waiting for your person 💛",
  linked: "You're linked! 🎉",
  noFight: "Duo shows facts about us, never accusations about you. No red. No alarms. Ever.",
};
